# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
sphinx:
  configuration: docs/conf.py
formats: all
python:
  version: 2.7
  install:
    - requirements: requirements/dev-requirements.txt
